name: Build SISO image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Build image
        run: ./build.sh
      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: siso-*.iso
